line_length: 120
disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - trailing_whitespace
  - large_tuple
  - closure_parameter_position
  - type_body_length
  - function_body_length
  - superfluous_disable_command
excluded:
  - Pods
  - RescueLink/Models/Heimdall.swift
